
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package usac.cunoc.interpretefiguras.logic.analysis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULTIPLICAR = 5;
  public static final int GREEN = 14;
  public static final int DIVIDIR = 4;
  public static final int SQUARE = 24;
  public static final int CURVE = 29;
  public static final int BLACK = 15;
  public static final int REAL_NUMEBERS = 8;
  public static final int CIRCLE = 20;
  public static final int BLUE = 11;
  public static final int RED = 12;
  public static final int ID = 7;
  public static final int GRAFICAR = 25;
  public static final int OBJECT = 28;
  public static final int COMA = 6;
  public static final int POLYGON = 22;
  public static final int MAROON = 19;
  public static final int ANIMATION = 26;
  public static final int EOF = 0;
  public static final int RECTANGLE = 23;
  public static final int CYAN = 16;
  public static final int RESTAR = 3;
  public static final int FUCHSIA = 17;
  public static final int PARENTESIS_C = 10;
  public static final int error = 1;
  public static final int LAST = 27;
  public static final int LAVENDER = 18;
  public static final int PARENTESIS_A = 9;
  public static final int LINE = 21;
  public static final int YELLOW = 13;
  public static final int SUMAR = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMAR",
  "RESTAR",
  "DIVIDIR",
  "MULTIPLICAR",
  "COMA",
  "ID",
  "REAL_NUMEBERS",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "BLUE",
  "RED",
  "YELLOW",
  "GREEN",
  "BLACK",
  "CYAN",
  "FUCHSIA",
  "LAVENDER",
  "MAROON",
  "CIRCLE",
  "LINE",
  "POLYGON",
  "RECTANGLE",
  "SQUARE",
  "GRAFICAR",
  "ANIMATION",
  "LAST",
  "OBJECT",
  "CURVE"
  };
}

